AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack Principal - Recursos do Projeto Serverless AWS

# Parâmetros globais
Parameters:
  WriterQueueName:
    Type: String
    Default: WriterQueue
  AccountTableName:
    Type: String
    Default: DataTable
  LogTableName:
    Type: String
    Default: LogTable
  RoleArn:
    Type: String
    Description: ARN of the IAM role for Lambda functions
  BucketName:
    Type: String
    Default: data-bucket-471112928175

Resources:
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./resources/
      Parameters:
  
  ObservabilityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./resources/
      Parameters:

  InfraStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./resources/
      Parameters:
  
  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./resources/
      Parameters:
Outputs:
  WriterQueueUrl:
    Description: "URL of the Writer SQS Queue"
    Value: !Ref WriterQueue