version = 0.1
[default.deploy.parameters]
stack_name = "serverless-it"
resolve_s3 = true
s3_prefix = "serverless-it"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "WriterQueueName=\"WriterQueue\" AccountTableName=\"AccountTable\" LogTableName=\"LogTable\" RoleArn=\"arn:aws:iam::471112928175:role/LabRole\" BucketName=\"data-bucket-471112928175\""
image_repositories = []
