# Doc Referencia https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack recursos IT

Parameters:
  TableName:
    Type: String
    Default: DataTable
  RoleArn:
    Type: String
    Description: ARN of the IAM role for Lambda functions
  BucketName:
    Type: String
    Default: data-bucket-370819

Globals:
  Function:
    Timeout: 25
    MemorySize: 128
    Runtime: provided.al2023
    Architectures:
      - x86_64

Resources:
#  DataBucket:
#    Type: AWS::S3::Bucket
#    Properties:
#      BucketName: !Ref BucketName
  WriterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: WriterQueue

#
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
#
#  RegisterFunction:
#    Type: AWS::Serverless::Function
#    Metadata:
#      BuildMethod: go1.x
#    Properties:
#      CodeUri: src/register/
#      Handler: bootstrap
#      Role: !Ref RoleArn
#      Environment:
#        Variables:
#          ENV: cloud
#          QUEUE_URL: !GetAtt WriterQueue.QueueUrl
#      Policies:
#        - SQSSendMessagePolicy:
#            QueueName: WriterQueue
#        - Statement:
#            - Effect: Allow
#              Action:
#                - logs:CreateLogGroup
#                - logs:CreateLogStream
#                - logs:PutLogEvents
#              Resource: '*'

#  TransformerFunction:
#    Type: AWS::Serverless::Function
#    Metadata:
#      BuildMethod: go1.x
#    Properties:
#      CodeUri: src/transformer/
#      Handler: bootstrap
#      Role: !Ref RoleArn
#      Environment:
#        Variables:
#          FUNCTION_NAME: !Ref RegisterFunction
#          ENV: cloud
#          QUEUE_URL: !GetAtt WriterQueue.QueueUrl
#      Events:
#        S3Event:
#          Type: S3
#          Properties:
#            Bucket: !Ref DataBucket
#            Events: s3:ObjectCreated:*
#
  WriterFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src/writer/
      Handler: bootstrap
      Role: !Ref RoleArn
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          ENV: cloud
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt WriterQueue.Arn
            BatchSize: 10
            Enabled: true
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TableName
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt WriterQueue.Arn
#
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
    Auth:
      DefaultAuthorizer: NONE

# Integration API Gateway -> SQS
  SqsIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGateway
      IntegrationType: AWS_PROXY
      IntegrationSubtype: SQS-SendMessage
      CredentialsArn: !Ref RoleArn
      RequestParameters:
        QueueUrl: !Ref WriterQueue
        MessageBody: "$request.body"
      PayloadFormatVersion: "1.0"

  #ApiGatewayPermission:
  #  Type: AWS::Lambda::Permission
  #  Properties:
  #    Action: lambda:InvokeFunction
  #    FunctionName: !Ref RegisterFunction
  #    Principal: apigateway.amazonaws.com
  #    SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/POST/register'
#
#