# Doc Referencia https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack recursos IT

Parameters:
  TableName:
    Type: String
    Default: DataTable
  RoleArn:
    Type: String
    Description: ARN of the IAM role for Lambda functions
  BucketName:
    Type: String
    Default: data-bucket-370819

Globals:
  Function:
    Timeout: 120
    MemorySize: 128
    Runtime: provided.al2023
    Architectures:
      - x86_64

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  WriterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: WriterQueue
      VisibilityTimeout: 300
#
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
#
#  RegisterFunction:
#    Type: AWS::Serverless::Function
#    Metadata:
#      BuildMethod: go1.x
#    Properties:
#      CodeUri: src/register/
#      Handler: bootstrap
#      Role: !Ref RoleArn
#      Environment:
#        Variables:
#          ENV: cloud
#          QUEUE_URL: !GetAtt WriterQueue.QueueUrl
#      Policies:
#        - SQSSendMessagePolicy:
#            QueueName: WriterQueue
#        - Statement:
#            - Effect: Allow
#              Action:
#                - logs:CreateLogGroup
#                - logs:CreateLogStream
#                - logs:PutLogEvents
#              Resource: '*'

  TransformerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src/transformer/
      Handler: bootstrap
      Role: !Ref RoleArn
      Environment:
        Variables:
          FUNCTION_NAME: !Ref RegisterFunction
          ENV: cloud
          QUEUE_URL: !GetAtt WriterQueue.QueueUrl
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref DataBucket
            Events: s3:ObjectCreated:*
#
  WriterFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src/writer/
      Handler: bootstrap
      Role: !Ref RoleArn
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          ENV: cloud
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt WriterQueue.Arn
            BatchSize: 10
            Enabled: true
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TableName
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt WriterQueue.Arn
#
  #ApiGateway:
  #  Type: AWS::Serverless::Api
  #  Properties:
  #    StageName: dev
  #    DefinitionBody:
  #      swagger: '2.0'
  #      info:
  #        title: EntryPointAPI
  #      paths:
  #        /register:
  #          post:
  #            x-amazon-apigateway-integration:
  #              uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RegisterFunction.Arn}/invocations'
  #              httpMethod: POST
  #              type: aws_proxy
  #    Auth:
  #      DefaultAuthorizer: NONE
#
  #ApiGatewayPermission:
  #  Type: AWS::Lambda::Permission
  #  Properties:
  #    Action: lambda:InvokeFunction
  #    FunctionName: !Ref RegisterFunction
  #    Principal: apigateway.amazonaws.com
  #    SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/POST/register'
#
#